
[project]
name = "Stopwatch"
version = "0.1.2"
description = "A simple stopwatch for recording time spent on activities"
authors = [{ name = "Caio" }]
readme = "README.md"
requires-python = ">=3.10"

[tool.pytest]
